using FluentAssertions;
using Penghou.Nuwa.Strategies;
using System.Text.Json.Nodes;

namespace Penghou.Nuwa.Tests;

/// <summary>
/// Exercises the self-contained text salvage strategy. These cases are
/// deliberately outside the handwritten recovery parser's grammar, so the
/// salvage phase is the only path that can succeed.
/// </summary>
public sealed class SalvageRepairStrategyTests
{
    private readonly SalvageRepairStrategy _strategy = new();

    [Fact]
    public void RepairAsync_StripsLineComments()
    {
        const string input =
            """
            {
              // generated by a model
              "name": "emit_files"
            }
            """;

        var root = Parse(input);

        root!["name"]!.GetValue<string>()
            .Should().Be("emit_files");
    }

    [Fact]
    public void RepairAsync_StripsHashAndBlockComments()
    {
        const string input =
            """
            {"name": "emit_files" # note
            /* trailing block */, "count": 2}
            """;

        var root = Parse(input);

        root!["count"]!.GetValue<long>()
            .Should().Be(2);
    }

    [Fact]
    public void RepairAsync_ConvertsPythonLiterals()
    {
        const string input =
            """{"active": True, "deleted": False, "extra": None}""";

        var root = Parse(input);

        root!["active"]!.GetValue<bool>()
            .Should().BeTrue();
        root["deleted"]!.GetValue<bool>()
            .Should().BeFalse();
        root.AsObject()
            .ContainsKey("extra").Should().BeTrue();
    }

    [Fact]
    public void RepairAsync_ConvertsSingleQuotedKeys()
    {
        const string input =
            """{'name': 'emit_files', 'count': 1}""";

        var root = Parse(input);

        root!["name"]!.GetValue<string>()
            .Should().Be("emit_files");
        root["count"]!.GetValue<int>()
            .Should().Be(1);
    }

    [Fact]
    public void RepairAsync_QuotesUnquotedKeysAndValues()
    {
        const string input =
            """{name: emit_files, count: 1}""";

        var root = Parse(input);

        root!["name"]!.GetValue<string>()
            .Should().Be("emit_files");
        root["count"]!.GetValue<int>()
            .Should().Be(1);
    }

    [Fact]
    public void RepairAsync_SkipsLeadingProseBeforeJson()
    {
        const string input =
            """
            Here is the JSON you asked for:
            {"name": "emit_files"}
            """;

        var root = Parse(input);

        root!["name"]!.GetValue<string>()
            .Should().Be("emit_files");
    }

    [Fact]
    public void RepairAsync_HandlesCombinedDamageViaFallback()
    {
        // Every defect here is outside the recovery grammar: a line comment,
        // a Python literal, an unquoted key, and a single-quoted key.
        const string input =
            """
            // model preamble
            {name: None, 'path': 'Program.cs'
            """;

        var root = Parse(input);

        root!.AsObject()
            .ContainsKey("name").Should().BeTrue();
        root["path"]!.GetValue<string>()
            .Should().Be("Program.cs");
    }

    [Fact]
    public void RepairAsync_EscapesRawControlCharactersInsideStrings()
    {
        const string input =
            "{\"note\":\"line1\nline2\tend\"}";

        var root = Parse(input);

        root!["note"]!.GetValue<string>()
            .Should().Be("line1\nline2\tend");
    }

    private JsonNode? Parse(string input)
    {
        var attempt = _strategy
            .RepairAsync(input)
            .GetAwaiter()
            .GetResult();

        attempt.Outcome.Should()
            .Be(RepairOutcome.Repaired);

        return JsonNode.Parse(attempt.Repaired!);
    }
}
