using FluentAssertions;

namespace Penghou.Nuwa.Tests;

/// <summary>
/// Exercises the self-contained text salvage pass that replaced the previous
/// external JSON-repair dependency. These cases are deliberately outside the
/// handwritten recovery parser's grammar, so the fallback is the only path
/// that can succeed.
/// </summary>
public sealed class TolerantJsonTextRepairTests
{
    [Fact]
    public void Parse_StripsLineComments()
    {
        const string input =
            """
            {
              // generated by a model
              "name": "emit_files"
            }
            """;

        var result = Parse(input);

        result.Succeeded.Should().BeTrue();
        result.Root!["name"]!.GetValue<string>()
            .Should().Be("emit_files");
    }

    [Fact]
    public void Parse_StripsHashAndBlockComments()
    {
        const string input =
            """
            {"name": "emit_files" # note
            /* trailing block */, "count": 2}
            """;

        var result = Parse(input);

        result.Succeeded.Should().BeTrue();
        result.Root!["count"]!.GetValue<long>()
            .Should().Be(2);
    }

    [Fact]
    public void Parse_ConvertsPythonLiterals()
    {
        const string input =
            """{"active": True, "deleted": False, "extra": None}""";

        var result = Parse(input);

        result.Succeeded.Should().BeTrue();
        result.Root!["active"]!.GetValue<bool>()
            .Should().BeTrue();
        result.Root!["deleted"]!.GetValue<bool>()
            .Should().BeFalse();
        result.Root!.AsObject()
            .ContainsKey("extra").Should().BeTrue();
    }

    [Fact]
    public void Parse_ConvertsSingleQuotedKeys()
    {
        const string input =
            """{'name': 'emit_files', 'count': 1}""";

        var result = Parse(input);

        result.Succeeded.Should().BeTrue();
        result.Root!["name"]!.GetValue<string>()
            .Should().Be("emit_files");
        result.Root["count"]!.GetValue<int>()
            .Should().Be(1);
    }

    [Fact]
    public void Parse_QuotesUnquotedKeysAndValues()
    {
        const string input =
            """{name: emit_files, count: 1}""";

        var result = Parse(input);

        result.Succeeded.Should().BeTrue();
        result.Root!["name"]!.GetValue<string>()
            .Should().Be("emit_files");
        result.Root["count"]!.GetValue<int>()
            .Should().Be(1);
    }

    [Fact]
    public void Parse_SkipsLeadingProseBeforeJson()
    {
        const string input =
            """
            Here is the JSON you asked for:
            {"name": "emit_files"}
            """;

        var result = Parse(input);

        result.Succeeded.Should().BeTrue();
        result.Root!["name"]!.GetValue<string>()
            .Should().Be("emit_files");
    }

    [Fact]
    public void Parse_HandlesCombinedDamageViaFallback()
    {
        // Every defect here is outside the recovery grammar: a line comment,
        // a Python literal, an unquoted key, and a single-quoted key.
        const string input =
            """
            // model preamble
            {name: None, 'path': 'Program.cs'
            """;

        var result = Parse(input);

        result.Succeeded.Should().BeTrue();
        result.Outcome.Should().Contain("tolerant text repair");
        result.Root!.AsObject()
            .ContainsKey("name").Should().BeTrue();
        result.Root["path"]!.GetValue<string>()
            .Should().Be("Program.cs");
    }

    [Fact]
    public void Parse_EscapesRawControlCharactersInsideStrings()
    {
        const string input =
            "{\"note\":\"line1\nline2\tend\"}";

        var result = Parse(input);

        result.Succeeded.Should().BeTrue();
        result.Root!["note"]!.GetValue<string>()
            .Should().Be("line1\nline2\tend");
    }

    private static TolerantJsonSyntaxTreeParseResult Parse(
        string input) =>
        new TolerantJsonSyntaxTreeParser().Parse(input);
}
